### ISSUE TITLE
The search function of this btree can not find the value

### ISSUE THREAD

**Issue by ypluo** [DICL/FAST_FAIR#10]
According to lines the btree_search() function member:
```cpp 
  page *t;
  while((t = (page *)p->linear_search(key)) == p->hdr.sibling_ptr) {
    p = t;
    if(!p) {
      break;
    }
  }
  if(!t || (char *)t != (char *)key) {
    printf("NOT FOUND %lu, t = %x\n", key, t);
    return false;
  }
```
linear_search() searchs a key in the leafnode and returns the corresponding value. Then the tree_search function compares the key with the found value in the leafnode, if doesn't match, takes it as not found and output a message. It is NOT right if the key and its corresponding value are not equivalent.

It has a few extra bugs with some special workloads: fastfair can not support zero value; it may run into fault when two consecutive Records has the same value;

**Comment by deukyeon** [comment]
Hello Yongping, 

Thanks for being interested in this project and reporting a bug.

I would like to add some comments to what you said.

**Comment by deukyeon** [comment]
Hello Yongping,

Thanks for being interested in this project and reporting bugs.

I would like to add some comments to what you said.
For the first issue, `fastfair can not support zero value`, Yes. 
If you meant that "zero value" is 0, it would be considered as NULL pointer which is used as a sentinel.
For the second one, `it may run into fault when two consecutive Records has the same value`, if two consecutive records which have the same value were inserted, I would say that the one with a greater key would be ignored by the FAST algorithm. Moreover, note that one of the assumptions of FAST and FAIR is that all pointers in B+-tree nodes are unique.

**Comment by ypluo** [comment]
Thanks for your kindly reply!

**Comment by ypluo** [comment]
Thanks for your kindly reply!
