### ISSUE TITLE
The consistency issue of the inner node search

### ISSUE THREAD

**Issue by zhangbowen-sjtu** [DICL/FAST_FAIR#16]
Hi all,

Thank you for sharing your work with the community. Recently, we find that the current implementation of lock-free inner node search may reach the incorrect child pointer due to the read-write conflict.

Consider the example below,  concurrent insert and search execute in the following order. The search operation may ignore the key of 10 in _(1)_ because its left and right pointers are the same due to an on-going shifting. Then, it might load the next key of 10 after the insert operation has been finished and return _ptr_ in the end. However, _p1_ is what the search operation expects to return.  The incorrect result is caused by the state change between two load operations.

```
    Search(3):				         (1) skip 10                (2) return ptr
    						    (p1=p1)                     (3<10)
                                                       v                          v
Insert(5,ptr): (p1,10,p2) --> (p1,10,p2,10,p2) --> (p1,10,p1,10,p2) --> (p1,5,ptr,10,p2)


```

A possible solution is to  maintain a "low_key" field in each inner node. Do you have any better solution towards this problem.

**Comment by deukyeon** [comment]
Thanks for being interested in our work. In my opinion, Search(3) should return NULL, not "ptr", because there is no element corresponding to the key(3).

**Comment by zhangbowen-sjtu** [comment]
> Thanks for your early reply.  As you said, there is no problem when performing leaf node search. However,  our example focuses on the inner node search. In this case, we expect to return p1 since the key of 3 lies within the range of 0-5.

**Comment by deukyeon** [comment]
Ah, sorry for the misunderstanding. I would say that another possible solution could be to retry searching whenever the node became dirty. Adding attributes to the header of a node makes a fanout decrease, possibly resulting in performance degradation. So it is usually good to keep headers as small as possible. You should do the math to get what size can be the max for headers. However, the retry approach could have disadvantages such as livelock and long tail-latency. I am not sure which one is better.

**Comment by zhangbowen-sjtu** [comment]
Thanks for the sharing! I think the method that retrying whenever the node became dirty is probably too pessimistic as the above situation happens very infrequently. How about only maintain the low_key in the leaf nodes? In this way, the search operations only need to retry when it reaches the wrong leaf.

**Comment by deukyeon** [comment]
That would be a better one. A caveat is that the larger the header size is, the less the number of fanouts is, as I mentioned. Do the math when you add a new attribute in a header.

**Comment by zhangbowen-sjtu** [comment]
Thank you!

**Comment by deukyeon** [comment]
No problem! Feel free to let me know if necessary. Let me close this issue.
