### ISSUE TITLE
Node destruction

### ISSUE THREAD

**Issue by olzhabay** [DICL/FAST_FAIR#2]
Can you please point, where do you make old node destruction, if split or merge occurs?
Want to use your source.

**Comment by deukyeon** [comment]
1) When a node splits, node destruction is not necessary.
2) Node merge
In the current implementation, we don't merge nodes for the concurrent performance.
(You can find a paper referred in the source code.) 
For a single threaded version, I will check the part of the source to deallocate a node. 

If you have any question more, please feel free to ask me or another author.
