### ISSUE TITLE
WORT & FPTree Open Source

### ISSUE THREAD

**Issue by KinderRiven** [DICL/FAST_FAIR#3]
Hello, I would like to ask if you can open source WORT and FPTree source code, if you can, thank you very much~~~~~~QAQ

**Comment by deukyeon** [comment]
Hello, Thanks for your interests!
Unfortunately, I am really sorry that I could not open those source codes without authors' opinion.
You might want to contact to authors directly.
For FPTree, you could find its algorithms in the paper.
